[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = "debuginfo"
lto = true
panic = "abort"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
itertools = "0.12.0"
nom = "7.1.3"
num = "0.4.1"
rayon = "1.10.0"
rustc-hash = "2.1.0"
